---
title: Household Survey
---

## Household Survey Guidance

### 1. Introduction

A core part of our work is the regular collection of fisheries data and feedback to communities so that they can make informed management decisions. For communities to better understand changes to their fishery (i.e. if they are stable, increasing or decreasing), we must also understand changes in socio-economic factors and perceptions of fisheries management. Additionally, we must monitor the outcomes of projects in the communities where we work, so that we can make informed decisions on the next iterations of project activities. 

We recommend our partners to capture this information using a standardised Household survey (HHS). By collecting this data over time, we can better understand the impact of our work and support communities to create adaptive management plans that incorporate socioeconomic considerations.

The data collected in the HHS can provide evidence of impacts following activities across all pillars of our work: community-based fisheries management, secure rights, food security and financial inclusion (Figure 1). 

Figure 1. Blue Ventures' four-pillar model: community-based fisheries management, secure rights, food security and financial inclusion, all anchored by community data. The HHS forms a core part of the community data piece.

This document is designed for Blue Ventures colleagues and partners conducting the HHS. It outlines what the HHS is, how to prepare for data collection, how to collect this data ethically, the safeguarding reporting processes to follow, how to calculate sample sizes, and some tips on interview techniques. 

A key piece of additional reading is the "[Guidance on ethical data collection](https://docs.google.com/document/d/17kfhMpF3xkUxH1xQCHo2lez71nEQoOu13NhcJoC_6xU/edit?tab=t.0)", which outlines the expected behaviours of those interacting with community members during the HHS. It is essential that everyone involved in the data collection process abides by these guidelines. This includes acting with respect and integrity, capturing free, prior and informed consent (FPIC), and having clear safeguarding reporting processes in place. More information can be found in section 4 of this guidance.

### 2. What is the HHS?

The HHS is a KoboToolbox based survey form designed to collect responses from individual households in a community. The questionnaire method uses a randomised design to select households (sample population) in a community to answer a fixed set of questions that can be used to establish baselines and provide evidence of positive (or negative) social outcomes following an intervention at the household level. This information is collated and the results are used as an estimate of the wider community context and perception. These data are sex disaggregated with a sample design aiming for a 50:50 split between male and female respondents among households. The survey should be repeated after 3 years of programme support to measure change. 

The household survey aims to provide basic information about a community's livelihoods, dependence on the local fishery, economic resilience, social capital, knowledge of fishing regulations, attitudes and participation toward fisheries management, trust in different stakeholder groups and perceptions of their future food and economic security. The survey is used to evaluate existing conditions relevant to community-based fisheries management, especially in respect to trust and perceptions / engagement with management and how that links to their own perceptions of resource status, income and food security. 

**Why do we need to do it?**

These data set a baseline and can be used to design and focus programme priorities as well as inform management suggestions and strategies. This is critical programme information to understand if engagement in community based management is resulting in measurable change.

Importantly, this data should inform data feedback sessions with the community so that they can better understand their social dynamics to adaptively manage the fishery. For example, if trust in management and engagement in management activities has increased, then this may signal a positive result which can be championed. Comparatively, if trust with the government remains low , then that can inform potential strategies to improve those relationships. Additionally, the results from the HHS should be supplemented with the fisheries monitoring when necessary to improve our understanding of both community and ecological dynamics at play.

The Data Science team has developed an interactive Social and Economic dashboard to present this information. For support in interpreting the results of the dashboard and designing data feedback sessions, please refer to the Social and Economic guidance page.

### 3. Preparing for data collection

#### i. Contextualising the HHS

It is essential that you spend time reviewing the HHS and contextualising it for the communities you are surveying. Where possible this may include hiding questions in the Kobo survey that may be inappropriate to ask, adding options for the drop down lists, adapting existing questions to capture local dynamics, and importantly, translating the survey into your local dialect. Please reach out to a member of the Data Science team to support you in this process.

#### ii. Create or update reference information

A core part of preparing for the HHS is ensuring that all reference file data is updated and managed in SmartSheet. Reference files are pre-filled lists of information that are used in surveys to standardise data entry. Populating the reference files in Smartsheets is time consuming so please ensure you give at least 2 weeks to complete this process. You can reach out to a member of the Data Science team to support you in Smartsheet, or visit the Reference files guidance page. Reference files & information that should be reviewed in advance of data collection include:

-   Locations (admin1_ref, admin2_ref, admin3_ref)

-   Partner organization names (org_ref)

-   Data collector names (data_collector_ref)

-   Gear names and types (gear_ref)

-   Local names of species fished (species_ref)

#### iii. Defining the area of interest

From the beginning, it's important to define the area of interest (AOI)  for the Household survey in order to create a data collection plan and sampling design. The AOI should be the population that you wish to learn about and be able to detect changes in responses. Typically, this would be the communities associated with a management unit or within a certain administrative district. For the purposes of this guidance, we will use 'management unit' as the area of interest in the below examples.

#### iv. Sensitising the community to data collection plans

Before collecting data you must allocate appropriate time and resources in sensitising the community to your data collection plans. This includes: 

-   Why are we collecting data with the community, including the benefits of being involved in the data collection in terms of increased knowledge on their fisheries for project activities.

-   Any anticipated costs (e.g. time, energy and potentially challenging conversations) - as well as how we will mitigate these risks.

-   When and where data collection will take place (e.g. time/dates and location).

-   When and where the data will be provided back to them (e.g. when you anticipate to do the first data feedback session).

-   Who will be involved in the data collection

-   Where their data will go, how it is protected and anonymised (e.g. see [Data sharing and privacy agreements](https://docs.google.com/document/d/1YWhpG6WfROorKc-ZojPuHaxiSwS27WNXkVUrNzXAfAw/edit?tab=t.0#heading=h.s592ecw8zsr5)).

-   The expected behaviours of data collectors and those involved with the data collection (e.g. as outlined in the [Guidance for ethical data collection](https://docs.google.com/document/d/17kfhMpF3xkUxH1xQCHo2lez71nEQoOu13NhcJoC_6xU/edit?tab=t.0)), so that they may raise grievances if they are unhappy with any behaviour.

-   How community members can raise grievances if they are unhappy with any part of the data collection process or if they have safeguarding concerns (see next step on Ethical data collection and safeguarding).

-   That this is an optional process and each household has the right to refuse participation (see section on capturing FPIC below).

### 4. Guidance on ethical data collection and safeguarding

We strive to ensure that we collect data with the communities responsibly, with integrity, and in a way that respects the dignity and rights of all participants. It is essential that all data collectors behave in a respectful and responsible manner with the community. It is the responsibility of Blue Ventures staff to ensure that your data collectors have received appropriate training on how to behave responsibly. 

#### i. Guidance on ethical data collection 

Our [Guidance for ethical data collection](https://docs.google.com/document/d/17kfhMpF3xkUxH1xQCHo2lez71nEQoOu13NhcJoC_6xU/edit?tab=t.0) outlines the expected behaviours of all data collectors (and those involved in the process) to follow throughout the data collection project. This includes behaving respectfully to all participants they are interacting with, capturing Free, Prior and Informed Consent (FPIC), and abiding by safeguarding principles and processes. It is essential that data collectors have received training on this from Blue Ventures staff and/or partners **prior to starting data collection**. This training ensures that our data collection activities contribute positively to both conservation outcomes and community well-being, while minimising any risks to participants.

#### ii. Safeguarding vulnerable groups of people

An important aspect of ethical data collection is safeguarding vulnerable groups of people. Vulnerable groups of people are included but not limited to: those facing exclusion or stigmatisation from social differences such as race, gender, ethnicity, sexuality, class or caste, social status, level of education, access to social networks, proximity to degraded environments, and resource dependence. 

Safeguarding refers to the practices, policies, and actions taken to protect individuals from harm, abuse, neglect, exploitation, or discrimination. It involves creating environments, systems, and procedures that ensure the safety, well-being, and rights of individuals are upheld, both in personal and organizational contexts. We must ensure our work throughout data collection, data feedback and reporting follows safeguarding principles, and does not perpetuate any existing inequalities within the communities. This includes some of the following principles:

-   Obtaining **FPIC** and ensuring participation is genuinely voluntary.

-   Ensuring there are clear **safeguarding reporting mechanisms** in place, including a designated data collection safeguarding focal point (see Box 1 below).

-   Special care must be taken to ensure that their **involvement does not place anyone at risk of harm, discrimination, or abuse**. 

-   Data collection **must not exploit vulnerable participants or communities for personal, organisational, or financial gain.**

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Box 1. Reporting safeguarding concerns**                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                             |
| You should identify a **data collection safeguarding focal point** when you roll out the HHS. This person is responsible for processing any concern or issues raised throughout the data collection project via the Blue Ventures safeguarding reporting channels. Please reach out to your regional safeguarding lead to receive appropriate training on how to identify and handle safeguarding concerns. |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### 5. Sampling households

Now we understand how to conduct the HHS ethically, the next step is to choose the households to survey. Sampling design is based around the area of interest (AOI), typically a management unit. The management units we work with can be very large, sometimes spanning many hundreds of households. Therefore, it is not always possible to collect data from every household within the management unit, so we often collect data from a representative sample of households. This is called the sample size.

#### i. Sample size

The ideal sample size (number of households) that we should survey across an AOI (such as a management unit) of any size is **162 households**. This means that your survey should aim to collect at **least 162 household** **responses** across the **whole** management unit. For example, if you are only surveying ½ of the management unit, you need to only survey a minimum of 81 households. You can then complete the remaining 81 households at an alternative time. 

You can of course do more samples than the minimum 162 households, if you so wish and as resources allow.

Why this recommendation?

This approach to sample size calculation is **focused on optimising data collection for detecting real, meaningful change in the data**. We use statistical concepts such as power and effect size to determine how much data should be collected to confidently detect a change. This approach is scientifically rigorous and reduces the risk of sampling too few or too many households. 

There may be cases when sampling 162 households across your management unit is not appropriate, and you may want to sample more or less households than this. If this is the case, please speak directly with the Data Science and Global/Regional Technical teams for support in deciding an appropriate sample size number based on your needs.

#### ii. Sampling design

The next step is to choose which 162 households to survey within your AOI. If your management unit has multiple communities, surveys should be conducted proportional to the number of households in each community. For example, more surveys should be completed in communities with a higher number of households. Less surveys will be completed in the communities with a lower number of households. The total number of households surveyed across all communities in the management unit will still equal 162. 

**For example:**

This AOI, let's call it Management Unit 1, comprises 3 communities (A, B and C), totalling to 2600 households across the whole AOI.

We must split 162 proportionately across the three communities so that we complete more surveys in communities that are larger, and less surveys in communities that are smaller:

+-------------------------------------------------+------------------------+-------------------------------+--------------------------+
| **Name of AOI**                                 |                        | **Management Unit 1**         |                          |
+-------------------------------------------------+------------------------+-------------------------------+--------------------------+
| **Name of community**                           | **Community A**        | **Community B**               | **Community C**          |
+-------------------------------------------------+------------------------+-------------------------------+--------------------------+
| **Number of households in community**           | 100                    | 500                           | 2000                     |
+-------------------------------------------------+------------------------+-------------------------------+--------------------------+
| **Proportional number of households to sample** | 100/2600\*100 = **4%** | 500/2600\*100 = **19%**       | 2000/2600\*100 = **77%** |
+-------------------------------------------------+------------------------+-------------------------------+--------------------------+
| **Number of households to sample**              | **4%** of 162 = **7**  | **19%** of 162 = **31**       | **77%** of 162 = **124** |
+-------------------------------------------------+------------------------+-------------------------------+--------------------------+

**If your AOI is very large** e.g. spread across multiple regions/districts with multiple communities (e.g. UKB MPA in Senegal) you will need to proportionately split the 162 at two levels: firstly across the regions/districts, and then secondly across the communities.

**For example:**

In the UKB management area there are 3 regions (Region A, Region B and Region C). The total number of households across the entire AOI (e.g. all 3 regions) is 3000. Region A = 2000 households split across 3 communities, Region B  = 250 households split across 1 community, and Region C = 750 households split across 3 communities. You must split the 162 proportionately across the regions first, and then the communities. For example:

1.  Proportionately split the 162 households across the three regions in the AOI, so that the larger regions are attributed a larger number of samples

2.  Proportionately split the samples in each region across communities, so that larger communities are attributed a larger number of samples

Please reach out to a member of Data Science or Global Technical Knowledge for support in calculating your sample size if needed.

#### iii. Household selection

Once the sample size has been calculated and you know how many households you should sample per village - you must **randomly** select households across the area to collect data from. You can do this by giving each household a number and then choosing numbers randomly to survey, for example.

This is important to maintain scientific rigour. You must:

-   Do not focus data collection in only one area of the village.

-   Move between different households. You should not collect data from only a few similar households.

-   Stick to the random survey selection as above. 

-   Do not be influenced by others when choosing households. 

#### iv. Respondent selection

A critical goal of the HHS is to obtain information that is representative of the entire household from both men and women. The following best practices are recommended for obtaining survey responses that accurately represent the entire household and ensure equal inclusion of both men and women as the primary respondents.

**Gender stratification**

Use a random number generator (e.g. Microsoft Excel RAND function or www.numbergenerator.org) to assign half of the households to a male respondent and half to a female respondent. If you are selecting every fifth house with a total sample size of 20, randomly assign 10 as a female respondent and 10 as a male respondent. An example could be assigning female respondent to household number 1, 3, 6, 7, 8, 13, 15, 18, 9, 10 and male respondent to household number 2, 4, 5, 11, 12, 14, 16, 17, 19, 20. Select a time of day for the survey when you believe either the respondent will be available (this is particularly important for ensuring a representative sample of female respondents).

For example: 100 households -\> 50 male, 50 female respondents 

Choose a respondent in the household that is capable of providing accurate answers for the entire household. If the primary respondent is unsure or unable to confidently address the questions for the entire household, consider consulting other individuals present in the household.

### 6. Free prior and informed consent (FPIC)

Now you know what households you are going to survey, you must be ready to capture FPIC from each household that you speak with. We have a standardised FPIC oral consent script which can be found in the Annex of this guidance. 

Capturing FPIC is different to just simply asking for "consent". It is more thorough, and matches international guidelines on how to capture consent across social science conservation programmes. FPIC stands for:

**Free** means we use no coercion, intimidation, inducement or manipulation to obtain consent from participants. 

**Prior** means that we seek consent far enough in advance of any authorisation or commencement of activities, and we respect the time requirements of community consultation and consensus processes. 

**Informed** means that we provide all information relating to the activity to communities in advance, including how their personal data will be collected, used and stored. We ensure the information is objective, accurate and presented in a manner or form that is understandable to communities. 

Relevant information includes: 

1.  The nature, size, pace, duration, reversibility and scope of any proposed data collection; 

2.  The reason(s) or purpose of the data collection; 

3.  The location of areas that will be affected; 

4.  The possible economic, social, cultural and environmental impacts on the community and their lands and resources, including potential risks and realistic benefits; 

5.  Personnel likely to be involved in the implementation of the project;

**Consent** means that data collection can only proceed if the household has agreed to continue. Households have the right to refuse their consent or to give consent on conditions that meet their needs, priorities and concerns. 

You may print a physical copy of this consent script for your data collectors so that they can read it **aloud to each household that they interact with**. The data collectors will then record whether the household provides consent or not directly in the Kobo form as a Y/N response. It is important that we also record the households that do not provide consent (i.e. N), as this allows us to calculate a "refuse response ratio". 

If a household refuses to continue with the interview, that is OK! Simply thank them for their time and move to the next nearest house. **Never force or persuade a household to participate in the data collection survey** - this would not mean the consent was "free"!

+-----------------------------------------------------------------------------------------------------------------------------+
| Please refer to Annex 1 for the Oral consent script that should be printed and read aloud to every household you interview. |
+-----------------------------------------------------------------------------------------------------------------------------+

### 6. Interview techniques

Once you have obtained FPIC, the data collectors can conduct the survey with the household. 

Here is some advice on the interview techniques, adapted from Willis, Desai and Potter (2006).

**Where and when to interview**

-   On average, it takes data collectors 45 minutes - 1 hour to complete the survey of one household (varying with data collector capacity and skills)

-   You will deliver thesurvey **ONLY** to households. You should not travel elsewhere in the community to interview people. You must only knock on households doors that have been selected during the sampling strategy.

-   You must follow the sampling strategy. You should not choose only your friends and family to sample, for example.

-   You will capture FPIC from each household you interview.

-   If the household does not provide consent, you may thank them and move to the next closest household. You should continue to do this until a household provides consent. You should then return to the sampling strategy. 

-   You will never persuade or force a household to participate if they do not want to.

-   You should choose a time and day where fishers, or members of the household who would be able to confidently answer questions relating to the fishery, will be in the house.

-   If there is no one in the household able to answer questions on the fishery, you should thank them and move to the next closest household. You should then resume the normal sampling procedure. 

-   You should ideally alternate between asking for a male and female respondent across the households.

**Asking questions**

-   You should ask your questions in a friendly, open manner.

-   You should try to build some level of rapport with the interviewee prior to starting the survey.

-   You should ask how long the interviewee has to answer questions and stick to that time.

-   The survey is **not** an interrogation - you should avoid asking your questions quickly and/or in an assertive manner. 

-   You should **not** persuade or influence the interviewee's response.

-   You should give your respondent time to develop their ideas and ask for clarification.

-   You should listen carefully to the respondents' answers and ensure they have interpreted your questions correctly.

-   You will provide the interviewee the opportunity to reject answering a question if they are uncomfortable. 

-   You will never force or persuade the respondent to answer questions they are not comfortable in answering.

    -   We encourage you to take particular care when asking interviewers questions regarding financial income and expenditure. It is also important to consider the family dynamics and how revealing information during the survey may result in potential conflict. We encourage data collectors to "read the room" on whether these questions are appropriate or not, and adapt accordingly.

**Accuracy**

-   You will choose a person in the household who can accurately answer questions on the fishery (alternating by male and female for each household).

-   If the person in the household cannot answer questions on the fishery, you may want to return to the household at an alternative time.

-   Some countries prefer to provide incentives for households to participate in the survey such as a very small prize e.g. a sticker, bar of soap, small financial incentive.

### 7. Practical considerations

For more practical guidance on how to prepare for the HHS please refer to this presentation [here.](https://docs.google.com/presentation/d/1PxXpZkOa_yAiLMxksHJT65oEmx4sAoAS49n6Kp0rEYQ/edit#slide=id.g2f68f927de7_0_34)

### References and additional reading

**References**

Hay, I. (2010) 'Ethical Practice in Geographical Research', in Clifford, N., French, S., and Valentine, G. (eds) Key Methods in Geography, p. 35.

Willis, K., Desai, V. and Potter, R. (2006) 'Interviews', in Doing Development Research. SAGE Publications Ltd, p. 144.

**Additional reading list (if of interest)**

[ConSoSci](https://consosci.org/en-us/Resources/Training-Library)- The Conservation Social Science Partnership is a collaborative group of social science researchers and conservation practitioners. The website houses an array of training resources and general guidance on how to conduct social science research ethically within international conservation organisations.

The Conservation Social Science Partnership has created a [30 minute video on ethical concepts for research involving people](https://consosci.org/en-us/Research-Ethics/Ethical-Concepts).

[A manual on Free, Prior and Informed Consent (FPIC)](https://www.forestpeoples.org/en/topics/agribusiness/training/2016/liberia-fpic-training-materials-communities-driving-seat) - a manual written by the Sustainable Development Institute 

["Communities in the Driving Seat: A Manual on Free Prior and Informed Consent"](https://www.forestpeoples.org/en/topics/agribusiness/training/2016/liberia-fpic-training-materials-communities-driving-seat) by the Sustainable Development Institute.

[A toolkit to support conservation by indigenous peoples and local communities](https://library.sprep.org/content/toolkit-support-conservation-indigenous-peoples-and-local-communities-building-capacity-and) - ICCA / ICUN guidelines

### Appendices

Appendix 1: Oral consent script (adapted from [ConSoSci](https://drive.google.com/file/d/1FEcbteg1tgWrV88tNjPmVlRtBdVgR7uJ/view))

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Oral consent script**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **Introduction**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Hello, my name is \[name of surveyor\]. I am from \[name of the organisation\], an organisation that works in \[focus of activities, e.g. marine management\]. I'm doing some data collection on the households in this area so we can learn more about livelihoods to improve our programmes. I wondered if you'd be interested in being involved?                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **\[Await confirmation and record response\]**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **\[If the subject confirmed yes\]** We are a marine conservation organisation that works with local fishers to help improve their fish catch, so that they may fish sustainably long into the future. We are working in \[name of the area\] and are collecting household information to support our programmes.                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **Survey details**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   The aim of the survey is to capture fisher household information such as perceptions of fishing-related activities, income sources, daily activities, main fish species caught, reliance on fish for food, and fishing that can be used to establish social baselines and provide evidence of positive social outcomes following project activities.                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| <!-- -->                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   If you are happy to proceed, I would have a conversation with you and talk you through the survey questions. It may take up to 45 minutes, but hopefully we can get through the questions faster. For this household, it would be great to speak with \[a male/female\] representative **\[depending on gender stratification of the household - see Sampling Households section of this guidance for more information\]**, however if they are not available to answer, we can speak to the next oldest person available. |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| <!-- -->                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   I will record your answers directly in KoboToolbox. I may also take some additional written notes for clarity.                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| <!-- -->                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   This study is in partnership with Blue Ventures. The personal information you share with me will not be passed to any third party apart from \[name of the organisation\] and Blue Ventures.                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| <!-- -->                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   What is said during this meeting is private. I will not be collecting personal or identifiable information from you like your name/age. All data will be kept confidential and anonymous and you will not be able to be traced back to your answers.                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   We will record the GPS coordinates of the location of this interview which may be used to understand locations where the HHS has taken place. GPS coordinates will be made anonymous.                                                                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| <!-- -->                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   The data from this survey will be published in Blue Ventures online dashboards, and only the in-country teams and \[name of the organisation\] will be able to view this data.                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   The data may contribute to scientific studies, however the information you provide will remain confidential and anonymous and will not be identifiable to you.                                                                                                                                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   We will plan to share this data back to your community in  \[time period\]                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **Risks**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| This survey may cover some potentially sensitive issues for you to discuss, including:                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   Monthly income amounts in the household                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   Differences between men and women in the household                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| To reduce any potential risks we support you in not answering any questions if they are too sensitive.                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Whilst there are no direct benefits of you contributing to this survey, the results of this survey will support the  \[name of the organisation\] to work with local fishers with the goal of improving fish catch for the community.                                                                                                                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Your participation in this research is completely voluntary:                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   You don't have to agree to take part.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   You can ask me any questions you want before or throughout.                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   You can also withdraw at any stage during the interview without giving a reason.                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| -   If you withdraw, all of the data we collected related to you will be destroyed.                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| If you have any complaints or concerns, please feel free to contact directly \[name of the focal point\] (please provide contact details)                                                                                                                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **Oral consent**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Do you have questions or concerns so far, or need me to clarify any point?                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **\[Pause here to give participant enough time to think and comment\]**                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Are you happy to take part in this research?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **\[Await a response and record the response in the KoboToolbox survey\]**                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
