---
title: Landings Profiling
echo: false
output: false
---

```{r}
library(shiny.i18n)
library(rmarkdown)
library(knitr)
i18n <- Translator$new(translation_csvs_path = "data")
i18n$set_translation_language("mg")
i18n


```

## KoboCollect - Landings Profiling

### `r { i18n$t("subtitle1") }`

| `r { i18n$t("question") }`    | `r { i18n$t("answer") }`         |
|----------------------|-------------------------------------------|
| `r { i18n$t("q1") }` |                                           |
| `r { i18n$t("q2") }` | org_ref                                   |
| `r { i18n$t("q3") }` | admin1_ref                                |
| `r { i18n$t("q4") }` | admin2_ref                                |
| `r { i18n$t("q5") }` | admin3_ref                                |
| `r { i18n$t("q6") }` | data_collector_ref / `r { i18n$t("a1") }` |
| `r { i18n$t("q7") }` |                                           |

: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}

### `r { i18n$t("subtitle2") }`

| `r { i18n$t("question") }`                    | `r { i18n$t("answer") }`                     |
|-------------------|-----------------------------------------------------|
| `r { i18n$t("q8") }`  | fisher_ref / `r { i18n$t("a2") }`                                                         |
| `r { i18n$t("q9") }`  | `r { i18n$t("a3") }` / `r { i18n$t("a4") }` / `r { i18n$t("a5") }` / `r { i18n$t("a6") }` |
| `r { i18n$t("q10") }` | `r { i18n$t("a7") }` / `r { i18n$t("a8") }`                                               |
| `r { i18n$t("q11") }` | admin1_ref                                                                                |
| `r { i18n$t("q12") }` | admin2_ref                                                                                |
| `r { i18n$t("q13") }` | admin3_ref                                                                                |
| `r { i18n$t("q14") }` |                                                                                           |
| `r { i18n$t("q15") }` |                                                                                           |
| `r { i18n$t("q16") }` | landing_site_ref / `r { i18n$t("a8.9") }`    |
| `r { i18n$t("q17") }` | fishing_ground_ref / `r { i18n$t("a9") }`      |
| `r { i18n$t("q18") }` | buyer_ref / `r { i18n$t("a10") }`             |
| `r { i18n$t("q19") }` | `r { i18n$t("a3") }` / `r { i18n$t("a4") }` / `r { i18n$t("a5") }` / `r { i18n$t("a6") }` |

: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}

### `r { i18n$t("subtitle3") }`

| `r { i18n$t("question") }`                    | `r { i18n$t("answer") }`                     |
|------------------|------------------------------------------------------|
| `r { i18n$t("q20") }` | `r { i18n$t("a11") }` / `r { i18n$t("a12") }` / `r { i18n$t("a13") }` / `r { i18n$t("a14") }` / `r { i18n$t("a14.5") }` /`r { i18n$t("a15") }` |
| `r { i18n$t("q21") }` |                                        |
| `r { i18n$t("q22") }` |                                        |
| `r { i18n$t("q23") }` | `r { i18n$t("a7") }` / `r { i18n$t("a8") }`    |
| `r { i18n$t("q24") }` | fisher_ref / `r  { i18n$t("a2") }`    |
| `r { i18n$t("q25") }` |                                        |
| `r { i18n$t("q26") }` | fisher_ref                             |
| `r { i18n$t("q27") }` | `r { i18n$t("a16") }` / `r { i18n$t("a17") }`     |

: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}

### `r { i18n$t("subtitle4") }`

| `r { i18n$t("question") }`                    | `r { i18n$t("answer") }`                     |
|----------------|--------------------------------------------------------|
| `r { i18n$t("q28") }` | \*species_group_ref            |
| `r { i18n$t("q29") }` | species_ref / `r { i18n$t("a18") }` / \*`r { i18n$t("a19") }` |
| `r { i18n$t("a18") }` |                                |
| `r { i18n$t("q30") }` |                                |
| `r { i18n$t("q31") }` |                                |
| `r { i18n$t("q32") }` |                                |
| `r { i18n$t("q33") }` |                                |
| `r { i18n$t("q34") }` |                                |
| `r { i18n$t("q35") }` |                                |
| `r { i18n$t("q36") }` | `r { i18n$t("a20") }` / `r { i18n$t("a21") }` / `r { i18n$t("a22") }` / `r { i18n$t("a23") }`            |
| `r { i18n$t("q37") }` |                                |
| `r { i18n$t("q38") }` | `r { i18n$t("a24") }` / `r { i18n$t("a25") }` / `r { i18n$t("a26") }` / `r { i18n$t("a27") }` / `r { i18n$t("a28") }` / `r { i18n$t("a29") }` / `r { i18n$t("a30") }`            |
| `r { i18n$t("q39") }` | \*`r { i18n$t("a31") }` / `r { i18n$t("a32") }` / `r { i18n$t("a33") }` / `r { i18n$t("a34") }`            |
| `r { i18n$t("q40") }` | \*                              |
| `r { i18n$t("q41") }` | \*                              |
| `r { i18n$t("q42") }` | \*                              |
| `r { i18n$t("q43") }` | \*                              |
| `r { i18n$t("q44") }` | \*                              |

: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}

### `r { i18n$t("subtitle5") }`

| `r { i18n$t("question") }`                    | `r { i18n$t("answer") }`                     |
|----------------|--------------------------------------------------------|
| `r { i18n$t("q45") }` |                                 |
| `r { i18n$t("q46") }` | `r { i18n$t("a35") }` / `r { i18n$t("a36") }` / `r { i18n$t("a37") }` / `r { i18n$t("a38") }`                                |
| `r { i18n$t("q47") }` |                                 |
| `r { i18n$t("q48") }` |                                 |
| `r { i18n$t("q49") }` |                                 |
| `r { i18n$t("q50") }` | \*`r { i18n$t("a39") }` / `r { i18n$t("a40") }` / `r { i18n$t("a41") }` / `r { i18n$t("a42") }` / `r { i18n$t("a43") }` / `r { i18n$t("a44") }` / `r { i18n$t("a45") }` / `r { i18n$t("a46") }` / `r { i18n$t("a47") }`        |
| `r { i18n$t("q51") }` |                                 |
| `r { i18n$t("q52") }` |`r { i18n$t("a48") }` / `r { i18n$t("a49") }` / `r { i18n$t("a50") }` / `r { i18n$t("a51") }` / `r { i18n$t("a52") }`      |

: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}

### `r { i18n$t("subtitle6") }`

| `r { i18n$t("question") }`   | `r { i18n$t("answer") }`                 |
|----------------|--------------------------------------------------------|
| `r { i18n$t("q53") }` | `r { i18n$t("a35") }` / `r { i18n$t("a36") }` / `r { i18n$t("a37") }` / `r { i18n$t("a38") }`                                |
| `r { i18n$t("q54") }` |                                 |
| `r { i18n$t("q55") }` |                                 |
| `r { i18n$t("q56") }` |                                 |
| `r { i18n$t("q57") }` | `r { i18n$t("a35") }` / `r { i18n$t("a36") }` / `r { i18n$t("a37") }` / `r { i18n$t("a38") }`                  |
| `r { i18n$t("q58") }` - `r { i18n$t("q67") }`|                                 |
| `r { i18n$t("q59") }` | `r { i18n$t("a53") }` / `r { i18n$t("a54") }`       |
| `r { i18n$t("q60") }` |                                 |
| `r { i18n$t("q61") }` |                                 |
| `r { i18n$t("q62") }` |                                 |
| `r { i18n$t("q63") }` |                                 |
| `r { i18n$t("q64") }` |                                 |
| `r { i18n$t("q65") }` |                                 |

: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}

### \*`r { i18n$t("subtitle7") }`

| `r { i18n$t("question") }`      | `r { i18n$t("answer") }`              |
|----------------|--------------------------------------------------------|
| \*`r { i18n$t("q67.5") }` | \*`r { i18n$t("a63") }` / `r { i18n$t("a64") }` / `r { i18n$t("a65") }` / `r { i18n$t("a66") }` / `r { i18n$t("a67") }`          |
| `r { i18n$t("q68") }` |                                 |
| `r { i18n$t("q69") }` | `r { i18n$t("a35") }` / `r { i18n$t("a36") }` / `r { i18n$t("a37") }` / `r { i18n$t("a38") }`                                  |
| `r { i18n$t("q70") }`  - `r { i18n$t("q67") }`|                                 |
| `r { i18n$t("q59") }` | `r { i18n$t("a53") }` / `r { i18n$t("a54") }`     |
| `r { i18n$t("q71") }` |                                 |
| `r { i18n$t("q72") }` |                                 |
| `r { i18n$t("q73") }` |                                 |
| `r { i18n$t("q74") }` |                                 |
| `r { i18n$t("q75") }` |                                 |
| `r { i18n$t("q76") }` |                                 |
| \*`r { i18n$t("q77") }` | `r { i18n$t("a77") }` / `r { i18n$t("a78") }` / `r { i18n$t("a79") }` / `r { i18n$t("a80") }`                                |
: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}


| `r { i18n$t("q78") }` - `r { i18n$t("sp1") }`           |
|----------------|--------------------------------------------------------|
| \*`r { i18n$t("q79") }` | `r { i18n$t("a55") }` / `r { i18n$t("a56") }` / `r { i18n$t("a57") }` / `r { i18n$t("a58") }`                                 |
| \*`r { i18n$t("q79.5") }` |                                 |
| \*`r { i18n$t("q80") }` | 1 / 2 / 3 / 4 / 5 |
| \*`r { i18n$t("q81") }` |                                 |
| \*`r { i18n$t("q82") }` | `r { i18n$t("a7") }` / `r { i18n$t("a8") }`     |
| \*`r { i18n$t("q83") }` | 0-20% / 20-40% / 40-60% / 60-80% / 80-100%      |
| \*`r { i18n$t("q84") }` | `r { i18n$t("a59") }` / `r { i18n$t("a60") }`     |
| \*`r { i18n$t("q85") }` | `r { i18n$t("a61") }` / `r { i18n$t("a62") }`     |
: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}


| `r { i18n$t("q86") }` - `r { i18n$t("sp2") }`           |
|----------------|--------------------------------------------------------|
| \*`r { i18n$t("q87") }` | `r { i18n$t("a7") }` / `r { i18n$t("a8") }`     |
| \*`r { i18n$t("q88") }` | `r { i18n$t("a7") }` / `r { i18n$t("a8") }`     |
| \*`r { i18n$t("q89") }` | `r { i18n$t("a7") }` / `r { i18n$t("a8") }`     |
| \*`r { i18n$t("q90") }` |  `r { i18n$t("a68") }` / `r { i18n$t("a69") }` / `r { i18n$t("a70") }`                 |
| \*`r { i18n$t("q91") }` | `r { i18n$t("a71") }` / `r { i18n$t("a72") }` / `r { i18n$t("a73") }`                                |
| \*`r { i18n$t("q92") }` | `r { i18n$t("a7") }` / `r { i18n$t("a8") }`     |
: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}


| `r { i18n$t("q93") }` - `r { i18n$t("sp1") }`           |
|------------------------------------------------------------------------|
| \*`r { i18n$t("q94") }` |                                   |
| \*`r { i18n$t("q95") }` - `r { i18n$t("a3") }` | `r { i18n$t("a74") }` / `r { i18n$t("a75") }` / `r { i18n$t("a76") }`     |
| \*`r { i18n$t("q95") }` - `r { i18n$t("a4") }` | `r { i18n$t("a77") }` / `r { i18n$t("a78") }` / `r { i18n$t("a79") }` / `r { i18n$t("a80") }`     |
| \*`r { i18n$t("q96") }` - `r { i18n$t("a3") }` | `r { i18n$t("a81") }` / `r { i18n$t("a82") }` / `r { i18n$t("a83") }`     |
| \*`r { i18n$t("q96") }` - `r { i18n$t("a4") }` | `r { i18n$t("a81") }` / `r { i18n$t("a82") }` / `r { i18n$t("a83") }` / `r { i18n$t("a84") }`     |
| \*`r { i18n$t("q97") }` |                                   |
| \*`r { i18n$t("q98") }` - `r { i18n$t("a3") }` | `r { i18n$t("a85") }` / `r { i18n$t("a86") }` / `r { i18n$t("a87") }`                            |
| \*`r { i18n$t("q99") }` - `r { i18n$t("a4") }` | `r { i18n$t("a88") }` / `r { i18n$t("a89") }` / `r { i18n$t("a90") }`  |
: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}


| `r { i18n$t("q100") }` - `r { i18n$t("sp1") }`           |
|------------------------------------------------------------------------|
| \*`r { i18n$t("q101") }` |                                  |
: {tbl-colwidths="\[50,50\]" .table .table-striped .table-hover}

\*`r { i18n$t("star") }`
